// Code generated by scripts/generate-routes.go. DO NOT EDIT.

package main

import (
	routepkg0 "github.com/xihale/rsshub-go/routes/github"
	routepkg1 "github.com/xihale/rsshub-go/routes/hackernews"
	routepkg2 "github.com/xihale/rsshub-go/routes/npm"
	routepkg3 "github.com/xihale/rsshub-go/routes/reddit"
	routepkg4 "github.com/xihale/rsshub-go/routes/techne98"
	routepkg5 "github.com/xihale/rsshub-go/routes/test"
)

func registerRoutePackages() {
	routepkg0.RegisterRoutes()
	routepkg1.RegisterRoutes()
	routepkg2.RegisterRoutes()
	routepkg3.RegisterRoutes()
	routepkg4.RegisterRoutes()
	routepkg5.RegisterRoutes()
}
