package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	routePackages, err := discoverRoutePackages("routes")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error walking routes directory: %v\n", err)
		os.Exit(1)
	}

	outputs := []string{
		filepath.Join("cmd", "routes_gen.go"),
		filepath.Join("scripts", "verify-routes", "register_gen.go"),
	}

	for _, outputPath := range outputs {
		if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Error creating directory for %s: %v\n", outputPath, err)
			os.Exit(1)
		}

		content := buildGeneratedImports(routePackages, "main")
		if err := os.WriteFile(outputPath, content, 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", outputPath, err)
			os.Exit(1)
		}
		fmt.Printf("Generated %d route imports in %s\n", len(routePackages), outputPath)
	}
}

func discoverRoutePackages(routesDir string) ([]string, error) {
	var routePackages []string

	err := filepath.Walk(routesDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		// Skip the routes directory itself and hidden directories.
		if path == routesDir || strings.HasPrefix(filepath.Base(path), ".") {
			return nil
		}

		// If it's a directory and contains non-test .go files, it's a route package.
		if info.IsDir() {
			hasGoFiles, err := hasNonTestGoFiles(path)
			if err != nil {
				return err
			}
			if !hasGoFiles {
				return nil
			}

			relPath, err := filepath.Rel(routesDir, path)
			if err != nil {
				return err
			}
			importPath := fmt.Sprintf("github.com/xihale/rsshub-go/routes/%s", relPath)
			routePackages = append(routePackages, importPath)
		}

		return nil
	})
	if err != nil {
		return nil, err
	}

	sort.Strings(routePackages)
	return routePackages, nil
}

func hasNonTestGoFiles(dir string) (bool, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false, err
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go") {
			return true, nil
		}
	}

	return false, nil
}

func buildGeneratedImports(routePackages []string, packageName string) []byte {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by scripts/generate-routes.go. DO NOT EDIT.\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", packageName))
	buf.WriteString("import (\n")
	for i, pkg := range routePackages {
		buf.WriteString(fmt.Sprintf("\troutepkg%d \"%s\"\n", i, pkg))
	}
	buf.WriteString(")\n")
	buf.WriteString("\n")
	buf.WriteString("func registerRoutePackages() {\n")
	for i := range routePackages {
		buf.WriteString(fmt.Sprintf("\troutepkg%d.RegisterRoutes()\n", i))
	}
	buf.WriteString("}\n")
	return buf.Bytes()
}
