// Code generated by scripts/generate-routes.go. DO NOT EDIT.

package server

import (
	_ "github.com/xihale/rsshub-go/routes/academia"
	_ "github.com/xihale/rsshub-go/routes/github"
	_ "github.com/xihale/rsshub-go/routes/hackernews"
	_ "github.com/xihale/rsshub-go/routes/npm"
	_ "github.com/xihale/rsshub-go/routes/onex"
	_ "github.com/xihale/rsshub-go/routes/reddit"
	_ "github.com/xihale/rsshub-go/routes/thirtysec"
)
